Routepages06
WildCodeSchool-2024-02/JS-lyon-0224-P3-geocode pull request #20
Opened 2024-06-17 13:19 UTC by Mike69lyon

Route pages 
home, profile,contact and about-us

2024-06-17 13:26 UTC, MaksimLsk approved these changes
good

2024-06-17 13:33 UTC, rostom44 approved these changes

2024-06-17 14:11 UTC, StoicFrenchDev requested changes

2024-06-17 14:11 UTC, StoicFrenchDev commented on client/src/pages/Aboutuspage.jsx
> +export default function Aboutuspage() {
Noms des fonctions à mettre à jour également

2024-06-18 05:36 UTC, StoicFrenchDev approved these changes

2024-06-18 05:36 UTC, merged