07 signup form
WildCodeSchool-2024-02/JS-lyon-0224-P3-geocode pull request #30
Opened 2024-06-19 13:22 UTC by koni0669

2024-06-19 13:28 UTC, rostom44 approved these changes
good

2024-06-19 15:24 UTC, wildmatthieu requested changes

2024-06-19 15:24 UTC, wildmatthieu commented on client/src/pages/SignUp.jsx
> +        } else if (validate && !validate(value)) {
condition à expliciter : 
`validate === ???` et `!validate(value) === ???`

À répercuter partout ailleurs dans le fichier

2024-06-20 11:59 UTC, wildmatthieu requested changes

2024-06-20 11:59 UTC, wildmatthieu commented on client/src/pages/SignUp.jsx
> +        } else if (password && value !== password) {
expliciter la condition : 
`password === ??? && ...`

2024-06-20 11:59 UTC, wildmatthieu commented on client/src/pages/SignUp.jsx
> +        } else if (passwordMinLength && value.length < passwordMinLength) {
expliciter la condition : 
`passwordMinLength === ??? && ...`

2024-06-20 14:24 UTC, merged