page contact
WildCodeSchool-2024-02/JS-lyon-0224-P3-geocode pull request #39
Opened 2024-06-24 12:09 UTC by Mike69lyon

création de page contact

2024-06-24 13:13 UTC, koni0669 approved these changes
ok

2024-06-24 13:20 UTC, StoicFrenchDev commented
Pending conflicts

2024-06-24 14:21 UTC, wildmatthieu requested changes

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +        } else if (validate && !validate(value)) {
explicitez la condition : 

validate === ??? && !validate(value) === ???

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +        } else if (minLength && value.length < minLength) {
explicitez la condition : 

minLength === ??? && ...

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +    if (validateInputs()) {
explicitez la condition : 
validateInputs() === ???

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.fullName && (
expliciter la condition : 

formErrors.fullName === ??? && ...

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.fullName && (
expliciter la condition

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.email && <div className="error">{formErrors.email}</div>}
expliciter la condition

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.subject && (
expliciter la condition

2024-06-24 14:21 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.contactMessage && (
expliciter la condition

2024-06-24 21:31 UTC, Mike69lyon reviewed
ok

2024-06-25 08:11 UTC, wildmatthieu approved these changes

2024-06-25 08:12 UTC, merged