35 contactpagefrotback
WildCodeSchool-2024-02/JS-lyon-0224-P3-geocode pull request #46
Opened 2024-06-26 08:25 UTC by Mike69lyon

lier le backend and frontend

2024-06-26 09:01 UTC, HazeFury commented on client/src/pages/ContactPage.jsx
> +          alert("Message Sent.");
les alerts sur une application, ça fait un peu vieux ^^

Préfère passer par un toast ou même juste du texte dans ton formulaire mais oublie le alert ;)

2024-06-26 09:03 UTC, HazeFury requested changes
c'était presque parfait mais tu as mis un alert en trop 😆 🤣 

A retirer du coup ^^

2024-06-26 15:39 UTC, wildmatthieu requested changes

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +        } else if (minLength && value.length < minLength) {
expliciter la condition : 
`minLength === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +    if (validateInputs()) {
expliciter la condition : 
`validateInputs() === ???`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +        if (result.success) {
expliciter la condition : 
`result.success === ???`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +            {formErrors.firstname && (
expliciter la condition : 
`formErrors.firstname === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +            {formErrors.lastname && (
expliciter la condition : 
`formErrors.lastname === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +            {formErrors.email && (
expliciter la condition : 
`formErrors.email === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +            {formErrors.subject && (
expliciter la condition : 
`formErrors.subject === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +            {formErrors.message && (
expliciter la condition : 
`formErrors.message === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +          {formErrors.form && <div className="error">{formErrors.form}</div>}
expliciter la condition : 
`formErrors.form === ??? && ...`

2024-06-26 15:39 UTC, wildmatthieu commented on client/src/pages/ContactPage.jsx
> +        } else if (validate && !validate(value)) {
expliciter les conditions : 
`validate === ??? && validate(value) !== ???`

2024-06-27 08:39 UTC, HazeFury commented on client/src/pages/ContactPage.jsx
>          } else if (minLength && value.length < minLength) {
expliciter la condition :

minLength === ??? && ...

2024-06-27 08:40 UTC, HazeFury requested changes
expliciter la condition :
minLength === ??? && ...

2024-06-27 09:13 UTC, wildmatthieu approved these changes

2024-06-27 09:14 UTC, merged